name: popax::blog
description: popax::blog
author: Popax21
url: https://popax21.dev
timezone: Europe/Vienna
timezone_short: CET

theme: lightspeed
plugins:
 - jekyll-seo-tag
 - jekyll-figure

collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title:output_ext"

autopages:
  enabled: true
  categories:
    title: "Posts in category :cat"
    permalink: "/blog/cat/:cat"
    silent: false
  collections:
    layouts: []

exclude:
 - "theme"
 - "*.nix"