sass:
  sass_dir: _sass
  style: expanded

pagination:
  enabled: true
  sort_field: 'date'
  sort_reverse: true

jekyll-figure:
  paragraphs: false

exclude:
  - README.md
  - COPYING

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

